# permissions for end users to edit appscales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: scaling
    app.kubernetes.io/managed-by: kustomize
  name: appscale-editor-role
rules:
- apiGroups:
  - api.vikasbadoni.com
  resources:
  - appscales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.vikasbadoni.com
  resources:
  - appscales/status
  verbs:
  - get
